// Stage Themes — Visual Environment Definitions for Cyber Dash Campaign
// Each theme drives world.js rendering, particle colors, ambience, and hazards

const STAGE_THEMES = {
  1: {
    id: 'escape_facility',
    name: 'Escape Facility',
    bgColor: '#020a0e',
    skyGrad: ['#020a0e', '#04151c', '#061f2a'],
    floorColor: '#0a1a20',
    floorGlow: '#00f3ff',
    buildingHue: 185,
    accentColor: '#00f3ff',
    fogColor: 'rgba(0, 243, 255, 0.04)',
    ambientColor: 'rgba(0, 200, 220, 0.06)',
    weather: 'dripping',
    particles: 'sparks',
    hazards: ['laser_grid', 'spinning_blade'],
    holograms: ['NEXUS AI', 'SECTOR 4', 'PURGE SEQUENCE'],
    trackStyle: 'concrete',
    buildingStyle: 'facility',
    lightningChance: 0,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.3,
    rainIntensity: 0
  },
  2: {
    id: 'neon_streets',
    name: 'Neon Streets',
    bgColor: '#080012',
    skyGrad: ['#080012', '#12001f', '#1a0030'],
    floorColor: '#100018',
    floorGlow: '#ff007f',
    buildingHue: 290,
    accentColor: '#ff007f',
    fogColor: 'rgba(255, 0, 127, 0.04)',
    ambientColor: 'rgba(180, 0, 200, 0.06)',
    weather: 'rain',
    particles: 'neon_drops',
    hazards: ['traffic', 'laser_gate', 'drone_swarm'],
    holograms: ['CYBER CITY', 'ZONE 7', 'NO TRESPASS'],
    trackStyle: 'asphalt',
    buildingStyle: 'downtown',
    lightningChance: 0.002,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.4,
    rainIntensity: 0.7
  },
  3: {
    id: 'cyber_market',
    name: 'Cyber Market',
    bgColor: '#0c0800',
    skyGrad: ['#0c0800', '#1a1000', '#261800'],
    floorColor: '#1a1000',
    floorGlow: '#ffcc00',
    buildingHue: 45,
    accentColor: '#ffcc00',
    fogColor: 'rgba(255, 200, 0, 0.03)',
    ambientColor: 'rgba(200, 150, 0, 0.05)',
    weather: 'none',
    particles: 'confetti',
    hazards: ['moving_platform', 'market_drone', 'falling_crate'],
    holograms: ['CYBER BAZAAR', 'DEAL TODAY', 'NEON GOODS'],
    trackStyle: 'market_tiles',
    buildingStyle: 'market',
    lightningChance: 0,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.2,
    rainIntensity: 0
  },
  4: {
    id: 'industrial_factory',
    name: 'Industrial Factory',
    bgColor: '#0e0500',
    skyGrad: ['#0e0500', '#1c0a00', '#2a1000'],
    floorColor: '#1a0800',
    floorGlow: '#ff6600',
    buildingHue: 25,
    accentColor: '#ff6600',
    fogColor: 'rgba(255, 80, 0, 0.05)',
    ambientColor: 'rgba(220, 80, 0, 0.07)',
    weather: 'steam',
    particles: 'embers',
    hazards: ['rotating_saw', 'steam_vent', 'robot_worker', 'falling_hammer'],
    holograms: ['FACTORY UNIT 7', 'DANGER ZONE', 'HAZMAT'],
    trackStyle: 'metal_grating',
    buildingStyle: 'factory',
    lightningChance: 0,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.6,
    rainIntensity: 0
  },
  5: {
    id: 'underground_metro',
    name: 'Underground Metro',
    bgColor: '#000510',
    skyGrad: ['#000510', '#000a1e', '#00102a'],
    floorColor: '#000820',
    floorGlow: '#3399ff',
    buildingHue: 220,
    accentColor: '#3399ff',
    fogColor: 'rgba(0, 100, 255, 0.04)',
    ambientColor: 'rgba(0, 80, 200, 0.05)',
    weather: 'none',
    particles: 'electric_sparks',
    hazards: ['moving_train', 'electric_rail', 'dark_tunnel'],
    holograms: ['METRO LINE 9', 'NEXUS RAIL', 'PLATFORM 7'],
    trackStyle: 'rail',
    buildingStyle: 'tunnel',
    lightningChance: 0.001,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.7,
    rainIntensity: 0
  },
  6: {
    id: 'sky_highway',
    name: 'Sky Highway',
    bgColor: '#020c18',
    skyGrad: ['#020c18', '#041828', '#083040'],
    floorColor: '#041220',
    floorGlow: '#00ccff',
    buildingHue: 200,
    accentColor: '#00ccff',
    fogColor: 'rgba(0, 180, 255, 0.06)',
    ambientColor: 'rgba(0, 150, 220, 0.08)',
    weather: 'wind',
    particles: 'clouds',
    hazards: ['flying_vehicle', 'wind_gust', 'floating_platform', 'anti_air'],
    holograms: ['SKY LANE 1', 'ALTITUDE 5KM', 'NEXUS AIR'],
    trackStyle: 'glass_bridge',
    buildingStyle: 'sky_towers',
    lightningChance: 0.003,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.5,
    rainIntensity: 0.3
  },
  7: {
    id: 'quantum_lab',
    name: 'Quantum Laboratory',
    bgColor: '#001210',
    skyGrad: ['#001210', '#002018', '#003020'],
    floorColor: '#001810',
    floorGlow: '#00ff88',
    buildingHue: 155,
    accentColor: '#00ff88',
    fogColor: 'rgba(0, 255, 150, 0.04)',
    ambientColor: 'rgba(0, 200, 120, 0.05)',
    weather: 'none',
    particles: 'quantum_orbs',
    hazards: ['teleport_portal', 'energy_trap', 'laser_grid', 'force_field'],
    holograms: ['QUANTUM CORE', 'NEXUS LAB', 'EXPERIMENT 7'],
    trackStyle: 'quantum_tiles',
    buildingStyle: 'laboratory',
    lightningChance: 0.002,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.4,
    rainIntensity: 0
  },
  8: {
    id: 'frozen_data_center',
    name: 'Frozen Data Center',
    bgColor: '#000a18',
    skyGrad: ['#000a18', '#001228', '#001e3a'],
    floorColor: '#001530',
    floorGlow: '#88ccff',
    buildingHue: 210,
    accentColor: '#88ccff',
    fogColor: 'rgba(100, 180, 255, 0.08)',
    ambientColor: 'rgba(80, 160, 220, 0.06)',
    weather: 'snow',
    particles: 'snowflakes',
    hazards: ['ice_floor', 'frozen_enemy', 'cryo_vent', 'ice_spike'],
    holograms: ['CRYO CORE', 'TEMP -40C', 'DATA FROZEN'],
    trackStyle: 'ice',
    buildingStyle: 'cryo_facility',
    lightningChance: 0,
    snowChance: 0.8,
    voidGlitch: false,
    fogDensity: 0.6,
    rainIntensity: 0
  },
  9: {
    id: 'digital_void',
    name: 'Digital Void',
    bgColor: '#000000',
    skyGrad: ['#000000', '#050005', '#0a000a'],
    floorColor: '#080008',
    floorGlow: '#bd00ff',
    buildingHue: 290,
    accentColor: '#bd00ff',
    fogColor: 'rgba(180, 0, 255, 0.06)',
    ambientColor: 'rgba(150, 0, 220, 0.08)',
    weather: 'glitch',
    particles: 'data_fragments',
    hazards: ['gravity_flip', 'invisible_platform', 'reality_glitch', 'void_spike'],
    holograms: ['NULL SPACE', 'ERROR 404', 'MATRIX CORRUPT'],
    trackStyle: 'void',
    buildingStyle: 'broken_digital',
    lightningChance: 0,
    snowChance: 0,
    voidGlitch: true,
    fogDensity: 0.8,
    rainIntensity: 0
  },
  10: {
    id: 'nexus_fortress',
    name: 'NEXUS Fortress',
    bgColor: '#100005',
    skyGrad: ['#100005', '#1e000a', '#2c0010'],
    floorColor: '#180008',
    floorGlow: '#ff0040',
    buildingHue: 350,
    accentColor: '#ff0040',
    fogColor: 'rgba(255, 0, 60, 0.05)',
    ambientColor: 'rgba(200, 0, 40, 0.07)',
    weather: 'fire',
    particles: 'fire_embers',
    hazards: ['elite_guard', 'security_drone', 'turret', 'force_barrier'],
    holograms: ['NEXUS HQ', 'INTRUDER ALERT', 'MAX SECURITY'],
    trackStyle: 'fortress',
    buildingStyle: 'nexus_tower',
    lightningChance: 0.004,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.5,
    rainIntensity: 0
  },
  11: {
    id: 'ai_core',
    name: 'AI Core — NEXUS PRIME',
    bgColor: '#f0f0f8',
    skyGrad: ['#f0f0f8', '#e0e8f8', '#d0d8f0'],
    floorColor: '#e8f0ff',
    floorGlow: '#ffffff',
    buildingHue: 220,
    accentColor: '#ffffff',
    fogColor: 'rgba(255, 255, 255, 0.12)',
    ambientColor: 'rgba(200, 220, 255, 0.15)',
    weather: 'energy_pulse',
    particles: 'white_orbs',
    hazards: ['nexus_laser', 'core_explosion', 'ai_drone'],
    holograms: ['NEXUS PRIME', 'CORE ACTIVE', 'TERMINATE ALL'],
    trackStyle: 'white_void',
    buildingStyle: 'ai_core',
    lightningChance: 0.01,
    snowChance: 0,
    voidGlitch: false,
    fogDensity: 0.9,
    rainIntensity: 0
  }
};

// Ability unlock mapping: which stage boss defeat unlocks which ability
const ABILITY_UNLOCKS = {
  1: 'air_dash',
  3: 'triple_jump',
  5: 'energy_shield',
  7: 'emp_blast',
  9: 'gravity_jump'
};

// Boss type assignments per stage
const STAGE_BOSS_TYPES = {
  1:  'mega_drone',
  2:  'traffic_warden',
  3:  'laser_spider',
  4:  'titan_mech',
  5:  'cyber_worm',
  6:  'gravity_hawk',
  7:  'quantum_ghost',
  8:  'ice_colossus',
  9:  'reality_ripper',
  10: 'nexus_titan',
  11: 'nexus_prime'
};

// Grading thresholds: score 0-100 maps to rank
const GRADE_THRESHOLDS = [
  { score: 95, rank: 'SSS' },
  { score: 88, rank: 'SS'  },
  { score: 75, rank: 'S'   },
  { score: 60, rank: 'A'   },
  { score: 40, rank: 'B'   },
  { score: 20, rank: 'C'   },
  { score: 0,  rank: 'D'   }
];

window.STAGE_THEMES     = STAGE_THEMES;
window.ABILITY_UNLOCKS  = ABILITY_UNLOCKS;
window.STAGE_BOSS_TYPES = STAGE_BOSS_TYPES;
window.GRADE_THRESHOLDS = GRADE_THRESHOLDS;
